### ISSUE TITLE
parse_active_view: No object matches name

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#39]
Another Maya 2016 only feature that breaks in 2015.

```python
preset = capture.parse_active_view()
# Error: No object matches name: hardwareRenderingGlobals.hwFogAlpha
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "c:\pythonpath\capture.py", line 378, in parse_active_view
#     return parse_view(panel, camera)
#   File "c:\pythonpath\capture.py", line 406, in parse_view
# ValueError: No object matches name: hardwareRenderingGlobals.hwFogAlpha # 
```

**Comment by BigRoy** [comment]
Seems to be the same attribute right?
This one would've actually been caught when tests are run in `2015` right?

**Comment by mottosso** [comment]
I still got it, not sure why. :(

**Comment by BigRoy** [comment]
One is from parsing. The other from applying? ;)
Did you remove the attribute from both the defaults dict as from the tests dict?

It's easier to put the apply methods in try, except to fix backwards compatibility. 

Not sure how otherwise we'd go about skipping for older versions. Should we store somewhere which attributes were added in what version? Basically every attribute would also hold a version number they were added when doing something like that.

**Comment by mottosso** [comment]
> Not sure how otherwise we'd go about skipping for older versions. Should we store somewhere which attributes were added in what version?

I've given this a go. Basically, just appending features from newer versions on module load.

Have a look and let me know what you think.

**Comment by BigRoy** [comment]
Yes, saw it pop up. Looks good.
